### ISSUE TITLE
Interface Schema Properties Example

### ISSUE THREAD

**Issue by shaggygi** [Azure/IoTPlugandPlay#12]
I noticed the table for [Interface Schema Property](https://github.com/Azure/IoTPlugandPlay/tree/master/DTDL#interface-schemas) shows required properties for `mapKey` and `mapValue`.  However, the [example](https://github.com/Azure/IoTPlugandPlay/tree/master/DTDL#interface-schema-examples) below table doesn't include the 2 said properties.

Is there a reason the properties are missing or am I overlooking something?  Thx

**Comment by briancr-ms** [comment]
Thanks! This is a copy-paste bug. The mapKey and mapValue properties are not part of interface schemas.

**Comment by briancr-ms** [comment]
Fixed in PR #16
