### ISSUE TITLE
Common Data Model and Open Data Initiative

### ISSUE THREAD

**Issue by shaggygi** [Azure/IoTPlugandPlay#15]
I originally added the following in issue #10, but feel there should be more detailed discussions/thoughts around the topic as DTDL & CDM could fit very nicely with each other.

> Another area to see how it could fit is the Open Data Initiative and Common Data Model that Microsoft is driving.
> 
> While I briefly looked at CDM, it seems like you could make standard entities for the telemetry, interfaces, commands and such based on the CDM standard instead. That way the data could be used with the same tooling, APIs, apps, services and systems that already work with CDM.

Any thoughts on how DTDL could be based on the CDM and eventual APIs/SDKs?

**Comment by briancr-ms** [comment]
Thanks for your interest in combining IoT data with CDM and ODI. We're looking at this. Let us know if you have any specific thoughts or problems you're trying to solve.
