### ISSUE TITLE
Incorrect example for "Enum"

### ISSUE THREAD

**Issue by yphuangms** [Azure/IoTPlugandPlay#22]
In following example, "enumValue" should be "value" based on "EnumValue" schema:
{
    "@type": "Telemetry",
    "name": "state",
    "schema": {
        "@type": "Enum",
        "enumValues": [
            {
                "name": "offline",
                "displayName": "Offline",
                **"enumValue"**: 1
            },
            {
                "name": "online",
                "displayName": "Online",
                **"enumValue"**: 2
            }
        ]
    }
}

**Comment by briancr-ms** [comment]
This is fixed with PR #30.
