### ISSUE TITLE
No schema/description for data type "Unit"

### ISSUE THREAD

**Issue by yphuangms** [Azure/IoTPlugandPlay#23]
In "Field" or "Telemetry" schema description, there exists "displayUnit" and "unit". For "displayUnit" is of data type "string", and "unit" is of data type "Unit", there's no description in further to define schema for "Unit". Is it a primitive data type? How does it looks like?

Thanks!

**Comment by mattias-kindborg-axis-communications** [comment]
Related to #27

**Comment by briancr-ms** [comment]
Thanks for your feedback. You're right that this preview is not complete in regards to the unit property and Unit metamodel class. In this preview release there's no way to use the unit property or create a custom Unit metamodel class. For now, only displayUnit is fully supported.
