### ISSUE TITLE
Question regarding telemetry types

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/IoTPlugandPlay#27]
Hi and thanks for the awesome documentation!

I have one question regarding the DTDL documentation where it is saying that the [telemetry `@type` should be `Telemetry`](https://github.com/Azure/IoTPlugandPlay/tree/master/DTDL#telemetry-properties). But then when I read the samples I see [a telemetry written as](https://github.com/Azure/IoTPlugandPlay/blob/master/samples/EnvironmentalSensor.interface.json#L32):

```
"@type": [
        "Telemetry",
        "SemanticType/Temperature"
      ],
```

I thought the type had to be the string `Telemetry`, but it seems that it is more capable than that. Is there any documentation regarding the `Telemetry` metamodel class?

**Comment by mattias-kindborg-axis-communications** [comment]
Semantic types seems like an awesome idea, and something we will look more into. Where can I read more on these predefined semantic types, are they documented somewhere?

Regarding our domain, I cannot say that we have any semantic types yet, we are doing fine with the ordinary types we've got. I'll try to remember to get back to you when we discover a type that may be common for many use cases.

**Comment by briancr-ms** [comment]
In the preview release, you can see and use semantic types in Azure IoT Central with preview features, described [here](https://docs.microsoft.com/en-us/azure/iot-central/quick-deploy-iot-central-pnp?toc=/azure/iot-central-pnp/toc.json&bc=/azure/iot-central-pnp/breadcrumb/toc.json). Azure IoT Central with preview features offers a free 7-day trial in the Central US and North Europe regions.

In Azure IoT Central, when you add a telemetry item or property to a plug & play interface, you can specify its semantic type. This is described in more detail in the [Set up a device template](https://docs.microsoft.com/en-us/azure/iot-central/howto-set-up-template-pnp?toc=/azure/iot-central-pnp/toc.json&bc=/azure/iot-central-pnp/breadcrumb/toc.json) how-to guide.
