### ISSUE TITLE
Links to existing capability models and interfaces

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/IoTPlugandPlay#28]
I am unable to find where the capability models and interfaces defined by Azure, e.g. `urn:azureiot:DeviceManagement:DeviceInformation:1`. I'm guessing this isn't the only one?

A device manufacturer would be better off implementing interfaces defined by Azure instead of defining their own proprietary, or isn't that your idea regarding your interfaces. I mean, a thermostat is a thermostat is a thermostat 😄

**Comment by briancr-ms** [comment]
The capability models and interfaces defined by Azure IoT are available in the model repository.

There are a couple ways to see the capability models and interfaces in the model repository.

1. Use the Azure IoT Tools extension in VS Code. There are instructions in the Prerequisite section on [this page](https://docs.microsoft.com/en-us/azure/iot-pnp/howto-develop-with-vs-vscode) that describe how to install the Azure IoT Tools extension. Once the extension is installed, press Ctrl+Shift+P (on Windows) to access the command list and search for "IoT Plug and Play: Open Model Repository...". Then select "Public repository". You'll see two tabs, one for viewing capability models and the other for viewing interfaces.
2. Use the Azure IoT CLI extension. There are instructions on [this page](https://docs.microsoft.com/en-us/azure/iot-pnp/howto-install-pnp-cli) that describe how to install the Azure IoT CLI extension. Once the extension is installed, the command `az iot pnp interface show -i urn:azureiot:DeviceManagement:DeviceInformation:1` will display the DeviceInformation interface.
