### ISSUE TITLE
Do the PNP only support C sample currently?

### ISSUE THREAD

**Issue by v-jiq** [Azure/IoTPlugandPlay#37]
At present, when I use vscode to generate framework code according to PNP file, it seems that only C version can be supported. Is it at the preview stage or has it been so ever since? If only C language is supported, how can I integrate code written in other languages,Is there any official advice?

**Comment by briancr-ms** [comment]
Yes, only C is supported as a code generation target in this preview release. However, Node.js support is shown in samples here: https://github.com/Azure-Samples/azure-iot-samples-node/tree/master/digital-twins.
