### ISSUE TITLE
A capability model can only implement one instance of each interface.

### ISSUE THREAD

**Issue by reginbald** [Azure/IoTPlugandPlay#52]
What is the rationale for this limitation? 
Would it not make sense to allow for reusability of interfaces within a Device Capability Model and across many? 
E.g. "robot A" that has two identical arms would use the same interface for both and "robot B" that has one arm identical to "robot A" would use the same interface.

**Comment by reginbald** [comment]
I guess this branch answers my question https://github.com/Azure/IoTPlugandPlay/tree/briancr-ms/dtdl-v2/DTDL 
@briancr-ms will this limitation be dropped in the next version?

**Comment by briancr-ms** [comment]
Yes we expect to drop this limitation in an upcoming release of the modeling language.
